apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: recipe-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:<YOUR_USERNAME>/sdx6ue.git  # Replace with your repo
    targetRevision: main
    path: recipe-chart
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
      parameters:
        - name: dbUser
          value: "recipe_user"
        - name: dbPassword
          value: "CHANGE_ME_USE_SEALED_SECRETS"
  destination:
    server: https://kubernetes.default.svc
    namespace: recipe-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
