apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "recipe-api.fullname" . }}
  labels:
    {{- include "recipe-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "recipe-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "recipe-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: recipe-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: DB_HOST
              value: {{ printf "%s-postgresql" .Release.Name | quote }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "recipe-api.fullname" . }}-db-credentials
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "recipe-api.fullname" . }}-db-credentials
                  key: DB_PASSWORD
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
